name:                holylisp
version:             0.1.0.0
github:              "dedifferentiator/holylisp"
license:             GPL-3
author:              "413x"
maintainer:          "dedifferentiator@protonmail.ch"
copyright:           "Copyright (c) 2021 dedifferentiator"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            The holiest of all lisps
category:            Compilers

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/dedifferentiator/holylisp#readme>

dependencies:
- base >= 4.7 && < 5
- colourista
- generic-lens
- optparse-applicative
- megaparsec
- mtl
- relude
- text

default-extensions:
  - BlockArguments
  - ConstraintKinds
  - DataKinds
  - DeriveGeneric
  - FlexibleContexts
  - GeneralizedNewtypeDeriving
  - OverloadedStrings
  - NoImplicitPrelude
  - StrictData
  - TypeApplications
  - TypeFamilies
  - TypeOperators

library:
  source-dirs: src
  ghc-options:
    - -O3
    - -fwrite-ide-info
    - -hiedir=.hie
    - -Wall

executables:
  hlisp:
    main:                Main.hs
    source-dirs:         hlisp
    ghc-options:
    - -O3
    - -fwrite-ide-info
    - -hiedir=.hie
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    # - -prof
    dependencies:
    - holylisp

  hlispi:
    main:                Main.hs
    source-dirs:         hlispi
    ghc-options:
    - -O3
    - -fwrite-ide-info
    - -hiedir=.hie
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    # - -prof
    dependencies:
    - holylisp


tests:
  hlisp-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - holylisp
    - hspec
